# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0adba6a7149edb691d4510df9e84e2d8b0c677d3a8d684efc80872f4ba29862a4ec337dc31809f5ce0b90abef5dbbdcb0a01f11bf61054b7d12c8585f2770723

test:
  secret_key_base: 8d7bd67cca15327b3e6f66cf1c91148686a7ea0dc732708c3332f1c3892d93fdea327c00667dcfc5014ebe292b3dceaa698bbe542d095d32e7358e5e95b07c81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
